# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from utils import load_pdf, load_web_page, extract_text_from_html, convert_to_document_format, split_documents, create_vector_store, answer_question
import sys

def main(input_source, question, source_type="url", auto_generate=False):
    if source_type == "pdf":
        documents = load_pdf(url=input_source)
    elif source_type == "url":
        html = load_web_page(input_source)
        text = extract_text_from_html(html)
        documents = convert_to_document_format(text)
    else:
        raise ValueError("source_type must be either 'pdf' or 'url'.")

    docs = split_documents(documents)
    db = create_vector_store(docs)

    if auto_generate:
        questions = [
            "What is the main topic?",
            "Who is the target audience?",
            "What services or features are mentioned?",
        ]
        for q in questions:
            print(f"\nQ: {q}")
            print(f"A: {answer_question(q, db)}")
    else:
        print(f"\nQ: {question}")
        print(f"A: {answer_question(question, db)}")

# Örnek kullanım
if __name__ == "__main__":
    input_source = "https://peerbie.com"
    question = "What is Peerbie?"
    source_type = "url"  # ya 'pdf' ya da 'url'
    auto_generate = True

    main(input_source, question, source_type, auto_generate)